---

- name: Install drush using composer
  shell: >
    composer require drush/drush:{{ php_drush_version | default("7.*") }}
    chdir=/tmp/

- name: Run composer install to drush dir
  shell: >
    composer install
    chdir=/tmp/vendor/drush/drush/

- name: Ensure that composer dir doesn't exist in /var/lib
  file:
    path: /var/lib/composer
    state: absent

- name: Move composer modules to /var/lib
  become_user: root
  shell: mv /tmp/vendor /var/lib/composer

- name: Create symlinks to drush bin
  become_user: root
  file:
    src: "/var/lib/composer/bin/{{ php_drush_bin }}"
    dest: "/usr/local/bin/{{ php_drush_bin }}"
    state: link

- name: Run drush dl for registry_rebuild
  shell: "drush dl registry_rebuild-7 -y"
  when: php_drush_rr and php_drush_version == "7"

- name: Change .drush dir permissions
  shell: find /home -type d -name ".drush" -exec chmod -R 2777 '{}' ';'
  when: php_drush_rr and php_drush_version == "7"
