---

- name: Install drush using composer
  shell: >
    composer require drush/drush:{{ php_drush_version | default("7.*") }}
    chdir=/tmp/

- name: Run composer install to drush dir
  shell: >
    composer install
    chdir=/tmp/vendor/drush/drush/
